#!/bin/bash
#
# create-pr.sh
#
# AI Agent 작업 결과에 대한 PR을 github-actions[bot]으로 생성하는 스크립트
#
# 사용법:
#   ./create-pr.sh <branch_prefix> <pr_title> [pr_body]
#
# 환경 변수:
#   GH_TOKEN: GitHub CLI 인증을 위한 토큰

set -o errexit -o nounset -o pipefail

BRANCH_PREFIX="${1:-task}"
PR_TITLE="${2:-chore: AI Agent automated changes}"
PR_BODY="${3:-Automated changes by AI Agent}"

# Git 사용자 설정 (github-actions[bot])
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"

# 변경사항 확인
if ! git status --porcelain | grep -q .; then
  echo "No changes to commit"
  exit 0
fi

# 브랜치 이름 생성 (타임스탬프)
BRANCH_NAME="${BRANCH_PREFIX}/bot-$(date +%Y%m%d-%H%M%S)"

# 브랜치 생성 및 체크아웃
git checkout -b "$BRANCH_NAME"

# 모든 변경사항 스테이징
git add -A

# 스테이징된 변경사항 확인
STAGED_FILES=$(git diff --cached --name-only)
if [[ -z "$STAGED_FILES" ]]; then
  echo "No staged changes"
  exit 0
fi

# 변경사항 정보 수집
CHANGES_STATUS=$(git status --short)
CHANGES_STAT=$(git diff --cached --stat HEAD)

# 커밋
git commit -m "${PR_TITLE}

Co-Authored-By: Atlas <atlas@jk.agent>"

# 브랜치 푸시
if ! git push -u origin "$BRANCH_NAME"; then
  echo "Failed to push branch $BRANCH_NAME"
  exit 1
fi

# PR Description 생성
FULL_PR_BODY=$(cat <<EOF
## Summary

${PR_BODY}

## Changes

\`\`\`
${CHANGES_STATUS}
\`\`\`

## Statistics

\`\`\`
${CHANGES_STAT}
\`\`\`

---
🤖 Generated by github-actions[bot] with Atlas
EOF
)

# PR 생성
if ! gh pr create \
  --title "$PR_TITLE" \
  --body "$FULL_PR_BODY" \
  --base main \
  --head "$BRANCH_NAME"; then
  echo "Failed to create PR for branch $BRANCH_NAME"
  exit 1
fi

echo "Pull request created successfully for branch $BRANCH_NAME"
